#!/usr/bin/env bash

#[--------------------------------------------------------------------------------------------]
setterm -foreground green -background black -store
#[--------------------------------------------------------------------------------------------]
sudo nano /etc/apt/sources.list
#[--------------------------------------------------------------------------------------------]
sudo apt-get update
sudo apt-get install -y --no-install-recommends bash-completion cups epiphany-browser figlet firmware-linux firmware-linux-free firmware-linux-nonfree gdm3 gimp git gnome-core gnome-menus gnome-shell-extension-dashtodock gnome-shell-extension-hide-activities gnome-shell-extension-weather gnome-tweak-tool gpart gparted libreoffice libreoffice-l10n-pt-br nautilus-admin openssh-client openssh-server printer-driver-cups-pdf qbittorrent sudo ttf-mscorefonts-installer vlc vlc-l10n wget x11-apps xinit xorg
#[--------------------------------------------------------------------------------------------]
sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt-get -y install --no-install-recommends ./google-chrome-stable_current_amd64.deb
sudo rm -rf google-chrome-stable_current_amd64.deb
sudo update-alternatives --set x-www-browser /usr/bin/google-chrome-stable
sudo update-alternatives --set gnome-www-browser /usr/bin/google-chrome-stable
#[--------------------------------------------------------------------------------------------]
sudo apt-get remove -y --purge gnome-games* gnome-characters* gnome-font-viewer* gnome-software* gnome-logs* gnome-music* gnome-color-manager* gnome-clocks* gnome-sound-recorder* gnome-system-monitor firefox-esr* xterm* synaptic* evolution gbrainy* cheese im-config* swell-foop* totem-common* baobab* simple-scan* yelp* transmission-common* transmission-gtk* seahorse* malcontent* rhythmbox* shotwell* gdebi* xterm* vim*

sudo apt-get -y autoremove
sudo apt-get -y clean

sudo rm -rf /usr/share/applications/nm-connection-editor.desktop
sudo rm -rf /usr/share/applications/org.gnome.Extensions.desktop
#[--------------------------------------------------------------------------------------------]
sudo echo "user-db:user
system-db:gdm
file-db:/usr/share/gdm/greeter-dconf-defaults" > /etc/dconf/profile/gdm

sudo mkdir /etc/dconf/db/gdm.d

sudo echo "[org/gnome/login-screen]
# Disable user list from login screen
disable-user-list=true" > /etc/dconf/db/gdm.d/00-login-screen

sudo dconf update
#[--------------------------------------------------------------------------------------------]
echo "Definir senha do usuário root"
sudo passwd root

sudo adduser deisy
sudo addgroup deisy sudo
sudo addgroup deisy bluetooth

sudo adduser loterica
sudo addgroup loterica sudo
sudo addgroup loterica bluetooth

sudo adduser ricardo
sudo addgroup ricardo sudo
sudo addgroup ricardo bluetooth

sudo adduser yuri
sudo addgroup yuri sudo
sudo addgroup yuri bluetooth
#[--------------------------------------------------------------------------------------------]
sudo gpg --decrypt --output /tmp/usuarios.tar.gz usuarios.tar.gz.gpg 
sudo tar -xvzf /tmp/usuarios.tar.gz -C /
sudo rm -rf /tmp/usuarios.*
#[--------------------------------------------------------------------------------------------]
sudo nano /etc/default/grub
sudo update-grub
#[--------------------------------------------------------------------------------------------]
sudo nano /etc/fstab
#[--------------------------------------------------------------------------------------------]
clear
echo
read -p "[<<<<<<<< Pressione ENTER para reiniciar o sistema >>>>>>>>]" x
sudo shutdown -r now
#[--------------------------------------------------------------------------------------------]
